RATIO_IMAGE_SIZE = 2;

LEVELS_OF_DIFFICULTY_LEVELS = {'easily' : 1, 'average' : 2, 'hard' : 3};

BLOCK_WIDTH = 32 * RATIO_IMAGE_SIZE;
BLOCK_HEIGHT = 32 * RATIO_IMAGE_SIZE;

SPRITE_BLOCK_GRASS_WIDTH = 64;
SPRITE_BLOCK_GRASS_HEIGHT = 64;

SPRITE_BLOCK_SPAWN_WIDTH = 64;
SPRITE_BLOCK_SPAWN_HEIGHT = 64;

BULLET_WIDTH = 4;
BULLET_HEIGHT = 4;

SPRITE_BULLET_WIDTH = 4;
SPRITE_BULLET_HEIGHT = 4;

SPRITE_BLOCK_WIDTH = 32;
SPRITE_BLOCK_HEIGHT = 32;

SPRITE_RUN_ZOMBIE_X = 35;
SPRITE_RUN_ZOMBIE_Y = 0;

SPRITE_ATTACK_ZOMBIE_X = 0;
SPRITE_ATTACK_ZOMBIE_Y = 450;

SPRITE_KILLED_ZOMBIE_X = 175;
SPRITE_KILLED_ZOMBIE_Y = 400;

SPRITE_ZOMBIE_WIDTH = 35;
SPRITE_ZOMBIE_HEIGHT = 50;

SPRITE_PLAYER_WIDTH = 60;
SPRITE_PLAYER_HEIGHT = 60;

SIZE_TEXT_ON_BUTTON = 15;

SPRITE_BUTTON_WIDTH = 626;
SPRITE_BUTTON_HEIGHT = 262;

DEFENCE_OBJECT_WIDTH = 38;
DEFENCE_OBJECT_HEIGHT = 48;

DESTROED_DEFENCE_OBJECT_WIDTH = 56;
DESTROED_DEFENCE_OBJECT_HEIGHT = 16;

PLAYER_WIDTH = 25 * RATIO_IMAGE_SIZE;
PLAYER_HEIGHT = 30 * RATIO_IMAGE_SIZE;

ZOMBIE_WIDTH = 15 * RATIO_IMAGE_SIZE;
ZOMBIE_HEIGHT = 25 * RATIO_IMAGE_SIZE;

JOINING_SPRITE_OBJECT_PLAYER = 20;
JOINING_SPRITE_OBJECT_ZOMBIE = 15;

IMAGE_GRASS = 'img/tex_trava.jpg';
IMAGE_SPAWN = 'img/Spawn.bmp';
IMAGE_BOX = 'img/Box.bmp';
IMAGE_STONE = 'img/Stone.bmp';
IMAGE_DEFEND_OBJECT = 'img/DefObj.bmp';
IMAGE_ZOMBIE_1 = 'img/ZOMBIE1.gif';
IMAGE_ZOMBIE_2 = 'img/ZOMBIE2.gif';
IMAGE_ZOMBIE_3 = 'img/ZOMBIE3.gif';
IMAGE_ZOMBIE_4 = 'img/ZOMBIE4.gif';
IMAGE_PLAYER = 'img/Player.gif';
IMAGE_DETH_DEFEND_OBJECT = 'img/DethDefObj.gif';
IMAGE_STANDART_BULLET = 'img/StandartBullet.png';
IMAGE_FONE_MENU = 'img/FoneMenu.jpg';
IMAGE_BUTTON = 'img/Button.jpg';

PLAYER_STEP = 40 * RATIO_IMAGE_SIZE;

ZOMBIE_STEP = 9 * RATIO_IMAGE_SIZE;

ZOMBIE_DISTANCE_ATTACK = 1;
ZOMBIE_DAMAGE = 5;
ZOMBIE_INTERVAL_BETWEENE_ATTACKS = 1000;
ZOMBIE_HEALTH = 35;

PLAYER_HEALTH = 100;
DEFENC_OBJECT_HEALTH = 100;

BULLET_DAMAGE = 35;
SPEAD_STANDART_BULLET = 220;